# Book settings
# Learn more at https://jupyterbook.org/customize/config.html

title: Portfólio de Ciência de Dados
author: Wolker Sanches Dias
email: wolker.sd@hotmail.com
logo: imagens/logo.png
copyright: "2024"
description: >- # this means to ignore newlines until "baseurl:"
  Este é um examplo de livro construído com Jupyter Books.


# Links para redes sociais (opcional)
social:

- type: "linkedin"
  url: "https://www.linkedin.com/in/wolkerdias/"

- type: "github"
  url: "https://github.com/wolkerdias/"

# Force re-execution of notebooks on each build.
# See https://jupyterbook.org/content/execute.html
execute:
  execute_notebooks: force
  stderr_output: "remove-warn"
  timeout: 120

# Define the name of the latex output file for PDF builds
latex:
  latex_documents:
    targetname: book.tex

# Add a bibtex file so that we can create citations
#bibtex_bibfiles:
#  - references.bib

# add require.js para que os gráficos plotly sejam exibidos
sphinx:
  config:
    html_js_files:
    - https://cdnjs.cloudflare.com/ajax/libs/require.js/2.3.4/require.min.js
    
    # Configurações de idioma
    language: pt-BR


# Information about where the book exists on the web
repository:
  url: https://github.com/WolkerDias/portfolio-cientista-de-dados  # Online location of your book
  path_to_book: docs  # Optional path to your book, relative to the repository root
  branch: master  # Which branch of the repository should be used when creating links (optional)

# Add GitHub buttons to your book
# See https://jupyterbook.org/customize/config.html#add-a-link-to-your-repository
html:
  toc:
    maxdepth: 5
    
  favicon: imagens/icon-machine-learning.svg
  use_issues_button: true
  use_repository_button: true
  home_page_in_navbar       : true

  analytics:
    google_analytics_id : "G-FDVQ6Q6M8H"   

  extra_footer: |
      <div style="text-align: center;">
        <a href="https://www.linkedin.com/in/wolkerdias" target="_blank">
          <img src="https://cdn-icons-png.flaticon.com/512/174/174857.png" alt="LinkedIn" style="width:40px;height:40px;margin:5px;transition:transform 0.3s;">
        </a>
        <a href="https://github.com/wolkerdias" target="_blank">
          <img src="https://cdn-icons-png.flaticon.com/512/25/25231.png" alt="GitHub" style="width:40px;height:40px;margin:5px;transition:transform 0.3s;">
        </a>
        <a href="mailto:wolker.sd@hotmail.com" target="_blank">
          <img src="https://cdn-icons-png.flaticon.com/512/281/281769.png" alt="Email" style="width:40px;height:40px;margin:5px;transition:transform 0.3s;">
        </a>
      </div>